version: "3.7"

services:
  club_app: &app
    build:
      context: .
    command: make docker-run-prod
    container_name: club_app
    environment:
      - DEBUG=false
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "8088:8088"

  queue:
    <<: *app
    command: make run-queue
    depends_on:
      - postgres
      - redis
    ports: []

  postgres:
    image: postgres:10
    restart: always
    container_name: club_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/10/main

  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
