version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile-production
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - DEBUG=false
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "8814:8814"

  queue:
    <<: *app
    command: make run-queue
    container_name: queue
    depends_on:
      - postgres
      - redis
    ports: []

  postgres:
    image: postgres:12
    restart: always
    container_name: club_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vas3k_club
    volumes:
      - ../postgresql:/var/lib/postgresql

  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  frontend:
    image: node:14-slim
    command: npm run build
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app/frontend
